import withNuxt from './.nuxt/eslint.config.mjs'

// Flat config generated by @nuxt/eslint; extend here as the project grows.
export default withNuxt(
  // Vendored reporting-kit bundle keeps its own conventions and CI — exclude it
  // from our ESLint (today it ships .md/.sh/.py, but guard future JS too).
  { ignores: ['reporting-kit/**'] }
)
