#!/usr/bin/env bash
# Register the CLIENT's own Priorbank business application on the client's server and write it
# into ./.env (docs/CLIENT_VERSION.md, step 4; «своя версия клиенту»).
#
# Why on the server and not on a developer machine: the private key that signs requests to the bank
# on the client's behalf must live ONLY in the client's .env. Generated here, inside the backend
# container, it never touches a laptop, a chat, a clipboard or the screen — and nobody has to paste
# a multi-line PEM into .env by hand (a truncated key is registered silently and fails only at the
# very last step, after the account owner has typed the bank password — docs/PRIOR_API.md,
# «invalid_request_object на authorize»).
#
# Steps:
#   1. key pair — RSA 2048, generated by node inside the `backend` container;
#   2. token A — client_credentials of the TECH application (production keys), Basic auth;
#   3. DCR — POST /register with `jwks`, the redirect on the client's domain and `private_key_jwt`;
#   4. read-back — GET /register/<clientId>, and the registered modulus is compared with ours.
#      ⚠ `PUT /register` answers 500 at this bank, so any mistake means a NEW registration; the
#      read-back is the only proof the registration is usable (docs/PRIOR_API.md);
#   5. .env — only after the read-back matched (backup first, owner and mode 600 kept);
#   6. --verify, after the Makefile recreated the containers: backend and worker both got the key,
#      and it is the registered one (the refresh runs in the worker).
#
# ⚠ The registration goes to https://api.priorbank.by:9344 directly, without the crypto gateway:
# confirmed by the owner 2026-09-28 on the client's server.
# ⚠ The subscriptions to the five APIs are NOT made here — there is no API for them; the operator
# does it in the bank's cabinet right after, and only then does `make prior-probe` get a token.
#
# ⚠ Secrets: the tech secret is typed with echo off and handed to node on STDIN (arguments are
# visible via /proc/<pid>/cmdline). The business client_secret and the key travel back on stdout,
# base64-wrapped, and go straight into .env; the screen shows the client_id and a fingerprint only.
#
# Usage (from the stack directory; normally through `make prior-register`):
#   bash prod-prior-register.sh "docker compose" 3>fp   # register, write .env; fingerprint on fd 3
#   bash prod-prior-register.sh --verify "docker compose" <fingerprint>   # after the restart

set -u

PRIOR_DCR_BASE="${PRIOR_DCR_BASE:-https://api.priorbank.by:9344}"
PRIOR_AUDIENCE='https://api.priorbank.by:9544/oauth2/token'
PRIOR_KID='client-key-1'

# ── Pure functions (tests/prodPriorRegister.test.ts loads them with a sed range) ───────────────

# Strip CR and surrounding whitespace: pasting from a phone brings them.
trim() {
  local s="${1//$'\r'/}"
  s="${s#"${s%%[![:space:]]*}"}"
  s="${s%"${s##*[![:space:]]}"}"
  printf '%s' "$s"
}

# A host name for the redirect: letters, digits, dots and dashes, at least one dot.
# ⚠ `[[ =~ ]]`, not grep: a value with a newline would pass grep on its first line, and the
# domain goes into .env, where a newline starts a new variable.
valid_domain() {
  local LC_ALL=C d="${1:-}"
  [[ "$d" =~ ^[A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?(\.[A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?)+$ ]]
}

# OAuth client ids and secrets of this bank are base64-ish tokens. The check is about .env safety:
# no quote, no space, no newline, no `$` — anything of the kind would change the meaning of the line.
valid_cred() {
  local LC_ALL=C v="${1:-}"
  [[ "$v" =~ ^[A-Za-z0-9._~+/=-]+$ ]]
}

# The redirect URI registered at the bank. The bank compares it byte for byte; nginx of the app
# turns this form into /api/bank/callback.
redirect_uri() {
  printf 'https://%s/oauth-priorbank-by/' "$1"
}

# The application name. It must be UNIQUE at the bank (a duplicate is 409), and ours is taken.
# ⚠ Latin only (owner's rule, 2026-09-29): the bank accepts Cyrillic, but the name is a technical
# identifier in the cabinet list; the human-readable text goes into the app DESCRIPTION in the cabinet.
default_app_name() {
  printf 'bank-import-%s' "${1//./-}"
}

valid_app_name() {
  [[ "$1" =~ ^[A-Za-z0-9._-]{3,100}$ ]]
}

# One field of the node output: result_field "<output>" CLIENT_ID → value (base64-decoded).
# ⚠ Only lines starting with the marker are read: the image preloads an OTel banner on stdout.
result_field() {
  printf '%s\n' "${1:-}" | sed -n "s/^PRIOR_REG_$2 //p" | head -1 | base64 -d 2>/dev/null
}

# Rewrite .env: drop every PRIOR_OAUTH_* line this registration owns (including a multi-line key
# left from a hand edit), append the new block.
# ⚠ Through a temporary file and `mv`: an interrupted `sed -i` could leave .env half-written.
# ⚠ The owner is copied from the old file and the mode is 600: run as root, a bitrix-owned .env
# would otherwise become root-only and the cron autodeploy would lose it.
ENV_TMP=""
# ⚠ It REFUSES (non-zero, .env untouched) rather than guesses: a quote that never closes, a key
# without its END marker, a foreign variable gone from the result, a key remnant left in it. Losing
# a line of .env silently (B24_TOKEN_ENC_KEY, DATABASE_URL…) breaks the server, and a leftover lone
# quote makes docker compose refuse the whole file — both were real risks, the second a live run.
# The script dry-runs this on a copy BEFORE the bank is contacted (see `preflight_env`).
rewrite_env() {
  local f="$1" block="$2" tmp
  tmp="$(mktemp "${f}.XXXXXX")" || return 1
  ENV_TMP="$tmp"
  if ! awk '
    function owned(line) {
      return line ~ /^[[:space:]]*(export[[:space:]]+)?PRIOR_OAUTH_(CLIENT_ID|CLIENT_SECRET|AUTH_METHOD|REDIRECT_URI|AUDIENCE|KID|PRIVATE_KEY|API_BASE|TOKEN_URL|AUTHORIZE_BASE)[[:space:]]*=/
    }
    closer != "" {
      # Inside a quoted multi-line value: skip up to and including the line with the closing quote.
      # The quote may sit on its own line after the END marker — a hand edit leaves exactly that.
      if (index($0, closer)) closer = ""
      next
    }
    skipping {
      # Inside an unquoted multi-line key: skip up to and including the END line — and ONLY the END
      # line ends it: the last base64 line of a PEM (`RGVm==`) looks like an assignment.
      if ($0 ~ /-----END/) skipping = 0
      next
    }
    pem_next {
      # An empty key value with the PEM on the following lines.
      pem_next = 0
      if ($0 ~ /^[[:space:]]*-----BEGIN/) { if ($0 !~ /-----END/) skipping = 1; next }
    }
    owned($0) {
      v = substr($0, index($0, "=") + 1)
      sub(/^[[:space:]]+/, "", v)
      sub(/[[:space:]\r]+$/, "", v)
      q = substr(v, 1, 1)
      if (q == "\"" || q == "\047") {
        # A quoted value that does not close on this line continues on the following lines.
        if (!index(substr(v, 2), q)) closer = q
      } else if ($0 ~ /PRIVATE_KEY/ && v == "") pem_next = 1
      else if ($0 ~ /PRIVATE_KEY/ && $0 ~ /-----BEGIN/ && $0 !~ /-----END/ && $0 !~ /\\n/) skipping = 1
      next
    }
    { print }
    END { if (closer != "" || skipping) exit 3 }
  ' "$f" > "$tmp"; then
    rm -f "$tmp"; ENV_TMP=""; return 1
  fi
  # Every foreign variable must survive (names read outside PEM bodies), and no key remnant may stay.
  local names='
    /-----BEGIN/ { pem = 1 } pem { if (/-----END/) pem = 0; next }
    match($0, /^[[:space:]]*(export[[:space:]]+)?[A-Za-z_][A-Za-z0-9_]*[[:space:]]*=/) {
      n = substr($0, RSTART, RLENGTH); sub(/^[[:space:]]*(export[[:space:]]+)?/, "", n); sub(/[[:space:]]*=$/, "", n)
      if (n !~ /^PRIOR_OAUTH_(CLIENT_ID|CLIENT_SECRET|AUTH_METHOD|REDIRECT_URI|AUDIENCE|KID|PRIVATE_KEY|API_BASE|TOKEN_URL|AUTHORIZE_BASE)$/) print n
    }'
  if [ -n "$(comm -23 <(awk "$names" "$f" | sort -u) <(awk "$names" "$tmp" | sort -u))" ] \
    || grep -qE -- '-----(BEGIN|END)|^[[:space:]]*["'"'"'][[:space:]]*$' "$tmp"; then
    rm -f "$tmp"; ENV_TMP=""; return 1
  fi
  if [ -s "$tmp" ] && [ -n "$(tail -c1 "$tmp")" ]; then printf '\n' >> "$tmp"; fi
  printf '%s\n' "$block" >> "$tmp"
  chown --reference="$f" "$tmp" 2>/dev/null \
    || echo "  ⚠ не удалось сохранить владельца .env — файл теперь принадлежит $(id -un); проверьте права" >&2
  if ! chmod 600 "$tmp" || ! mv "$tmp" "$f"; then
    rm -f "$tmp"; ENV_TMP=""; return 1
  fi
  ENV_TMP=""
}

# Dry run of rewrite_env on a copy — BEFORE the bank: after a registration a refusal would leave
# the only copy of the new key nowhere.
preflight_env() {
  local d rc
  d="$(mktemp -d)" || return 1
  cp -p "$1" "$d/.env" && rewrite_env "$d/.env" "X=1"
  rc=$?
  rm -rf "$d"
  return "$rc"
}

# The block written into .env. The key is ONE line with `\n` escapes inside double quotes — the form
# docker compose expands back into a PEM (and the one `make prior-probe` reads first).
env_block() {
  local id="$1" secret="$2" domain="$3" key_line="$4"
  printf '# Приорбанк — своя регистрация клиента (make prior-register, %s)\n' "$(date +%Y-%m-%d)"
  printf 'PRIOR_OAUTH_CLIENT_ID=%s\n' "$id"
  [ -n "$secret" ] && printf 'PRIOR_OAUTH_CLIENT_SECRET=%s\n' "$secret"
  printf 'PRIOR_OAUTH_AUTH_METHOD=private_key_jwt\n'
  printf 'PRIOR_OAUTH_REDIRECT_URI=%s\n' "$(redirect_uri "$domain")"
  printf 'PRIOR_OAUTH_AUDIENCE=%s\n' "$PRIOR_AUDIENCE"
  printf 'PRIOR_OAUTH_KID=%s\n' "$PRIOR_KID"
  printf 'PRIOR_OAUTH_API_BASE=%s\n' "$PRIOR_DCR_BASE"
  printf 'PRIOR_OAUTH_TOKEN_URL=%s/open-banking-authorize/v1.0/oauth2/token\n' "$PRIOR_DCR_BASE"
  printf 'PRIOR_OAUTH_PRIVATE_KEY="%s"' "$key_line"
}

# Code run by node INSIDE the backend container. Input — JSON on stdin; output — marker lines with
# base64 values. The registration metadata MUST equal `buildRegistrationMetadata` of
# app/utils/priorOauth.ts (that file is not on the server) — tests/prodPriorRegister.test.ts
# compares the body this code sends with it.
# ⚠ The bank's error TEXT never reaches the screen: a bank may echo the request back, and the request
# carries the tech secret (the same rule as for the Alfa API key). Only the HTTP status and the
# RFC 6749 machine code (`invalid_client`, …) are passed on — a code is a short lowercase word by
# definition, anything else is dropped.
REGISTER_JS='
const crypto = require("crypto");
let raw = "";
process.stdin.on("data", d => raw += d).on("end", async () => {
  const out = (k, v) => process.stdout.write("\nPRIOR_REG_" + k + " " + Buffer.from(String(v ?? "")).toString("base64") + "\n");
  const code = e => { const c = String(e ?? ""); return /^[a-z_]{1,40}$/.test(c) ? c : ""; };
  const fail = (stage, status, e) => { out("STAGE", stage); out("STATUS", status); out("ERROR", code(e)); out("OK", "0"); };
  try {
    const i = JSON.parse(raw);
    const { privateKey } = crypto.generateKeyPairSync("rsa", { modulusLength: 2048 });
    const pem = privateKey.export({ type: "pkcs8", format: "pem" });
    const jwk = crypto.createPublicKey(privateKey).export({ format: "jwk" });
    const jwks = { keys: [{ ...jwk, kid: i.kid, use: "sig", alg: "RS256" }] };
    const sig = () => AbortSignal.timeout(45000);
    const basic = "Basic " + Buffer.from(i.techId + ":" + i.techSecret).toString("base64");
    const tr = await fetch(i.base + "/open-banking-authorize/v1.0/oauth2/token", {
      method: "POST", signal: sig(),
      headers: { Authorization: basic, "Content-Type": "application/x-www-form-urlencoded", Accept: "application/json" },
      body: new URLSearchParams({ grant_type: "client_credentials", scope: "apim:subscribe apim:app_manage" })
    });
    const tj = await tr.json().catch(() => null);
    if (!tr.ok || !tj || !tj.access_token) return fail("token", tr.status, tj && tj.error);
    const auth = { Authorization: "Bearer " + tj.access_token, Accept: "application/json" };
    const meta = {
      client_name: i.name,
      redirect_uris: [i.redirect],
      response_types: ["code", "code id_token"],
      grant_types: ["authorization_code", "client_credentials", "refresh_token"],
      application_type: "web",
      id_token_signed_response_alg: "RS256",
      request_object_signing_alg: "RS256",
      token_endpoint_auth_method: ["private_key_jwt"],
      jwks: JSON.stringify(jwks)
    };
    const rr = await fetch(i.base + "/open-banking-dcr/v1.0/register", {
      method: "POST", signal: sig(), headers: { ...auth, "Content-Type": "application/json" }, body: JSON.stringify(meta)
    });
    const rj = await rr.json().catch(() => null);
    if (!rr.ok || !rj || !rj.client_id) return fail("register", rr.status, rj && rj.error);
    // Read-back: the slash before the id is required — without it the path lands on the POST route.
    const gr = await fetch(i.base + "/open-banking-dcr/v1.0/register/" + encodeURIComponent(rj.client_id), { signal: sig(), headers: auth });
    const gj = await gr.json().catch(() => null);
    let rk = gj && gj.jwks;
    if (typeof rk === "string") { try { rk = JSON.parse(rk) } catch { rk = null } }
    const keys = (rk && Array.isArray(rk.keys)) ? rk.keys : [];
    const rn = (keys.find(k => k.kid === i.kid) || keys[0] || {}).n || "";
    const fp = s => s ? crypto.createHash("sha256").update(s).digest("hex").slice(0, 16) : "";
    out("CLIENT_ID", rj.client_id);
    out("CLIENT_SECRET", rj.client_secret || "");
    out("KEY_LINE", pem.trim().split("\n").join("\\n") + "\\n");
    out("FP", fp(jwk.n));
    out("READ_STATUS", gr.status);
    out("READ_FP", fp(rn));
    out("READ_REDIRECT", JSON.stringify((gj && gj.redirect_uris) || []));
    out("READ_AUTH", JSON.stringify((gj && gj.token_endpoint_auth_method) || []));
    out("OK", "1");
  } catch (e) {
    fail("network", "", String((e && e.cause && e.cause.code) || "").toLowerCase());
  }
});'

# Code run by node inside a container after the restart: does the key parse, which one is it.
VERIFY_JS='
const crypto = require("crypto");
const e = process.env;
let fp = "bad";
try {
  const n = crypto.createPublicKey(crypto.createPrivateKey(e.PRIOR_OAUTH_PRIVATE_KEY || "")).export({ format: "jwk" }).n;
  fp = crypto.createHash("sha256").update(n).digest("hex").slice(0, 16);
} catch {}
process.stdout.write("\nVERIFY fp=" + fp + " method=" + (e.PRIOR_OAUTH_AUTH_METHOD || "-") + " client=" + (e.PRIOR_OAUTH_CLIENT_ID ? "set" : "-") + "\n");'

# One field of a VERIFY line.
verify_field() {
  printf '%s\n' "${1:-}" | tr ' ' '\n' | sed -n "s/^$2=//p" | head -1
}

# ── Check after the restart ───────────────────────────────────────────────────────────────────────
verify() {
  local dc="${1:-docker compose}" want="${2:-}" svc out line i tries="${VERIFY_TRIES:-30}" rc=0 fp method client
  printf '\n── Проверка: дошёл ли ключ до контейнеров ──\n'
  for svc in backend worker; do
    line=""
    for i in $(seq 1 "$tries"); do
      out="$($dc exec -T "$svc" node -e "$VERIFY_JS" 2>/dev/null)"
      line="$(printf '%s\n' "$out" | grep '^VERIFY ' | tail -1)"
      [ -n "$line" ] && break
      sleep 2
    done
    fp="$(verify_field "$line" fp)"; method="$(verify_field "$line" method)"; client="$(verify_field "$line" client)"
    if [ -z "$line" ]; then echo "  ✗ $svc не ответил — смотрите make ps и make logs"; rc=1; continue; fi
    if [ "$fp" = "bad" ]; then echo "  ✗ $svc: ключ не читается — .env не дошёл до контейнера или испорчен"; rc=1; continue; fi
    if [ -n "$want" ] && [ "$fp" != "$want" ]; then
      echo "  ✗ $svc: ключ НЕ тот, что зарегистрирован в банке (отпечаток $fp, ждали $want)"; rc=1; continue
    fi
    if [ "$method" != "private_key_jwt" ] || [ "$client" != "set" ]; then
      echo "  ✗ $svc: нет PRIOR_OAUTH_CLIENT_ID или метод не private_key_jwt"; rc=1; continue
    fi
    echo "  ✓ $svc: ключ зарегистрированный (отпечаток $fp), метод private_key_jwt"
  done
  [ "$rc" -eq 0 ] || return 1
  echo
  echo "Дальше, в кабинете Магазина API банка: оформить этому приложению ПЯТЬ подписок —"
  echo "  Open-banking-authorize, Open-banking-DCR, Open-banking, Open-banking-info, Authorize."
  echo "И описание приложения (карандаш в его строке): «Импорт выписки в Bitrix24 (<домен приложения>)»."
  echo "Потом проверка токеном: make prior-probe"
}

# ── Input and output from here on ────────────────────────────────────────────────────────────────

if [ "${1:-}" = "--verify" ]; then
  verify "${2:-docker compose}" "${3:-}"
  exit $?
fi

DC="${1:-docker compose -f docker-compose.prod.yml}"

[ -f ./.env ] || { echo "✗ ./.env не найден — запускайте из каталога со стеком"; exit 1; }
[ -t 0 ] || { echo "✗ ключи техприложения вводятся с клавиатуры — запустите команду в терминале"; exit 2; }
preflight_env ./.env || {
  echo "✗ не могу безопасно заменить блок PRIOR_OAUTH_* в .env: незакрытая кавычка, ключ без строки END"
  echo "  или строка, которую нельзя отнести ни к одной переменной. Банк не трогал, .env не менял —"
  echo "  поправьте блок PRIOR_OAUTH_* в .env и запустите команду снова."
  exit 1
}

env_value() {
  sed -n "s/^[[:space:]]*\(export[[:space:]][[:space:]]*\)\{0,1\}$1[[:space:]]*=//p" ./.env | head -1 \
    | sed -e 's/^[[:space:]]*"\(.*\)"[[:space:]]*$/\1/' -e "s/^[[:space:]]*'\(.*\)'[[:space:]]*\$/\1/"
}

printf '── Регистрация приложения Приорбанка для этого сервера ──\n\n'

OLD_ID="$(env_value PRIOR_OAUTH_CLIENT_ID)"
[ -n "$OLD_ID" ] && echo "Сейчас в .env: PRIOR_OAUTH_CLIENT_ID=$OLD_ID — будет ЗАМЕНЁН новой регистрацией."

# ⚠ Connected Prior accounts hold refresh tokens issued to the OLD client_id: after the switch they
# stop working and the account owner has to connect again. Ask before breaking them.
CONNECTED="$($DC exec -T db sh -c 'psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -At -c "SELECT count(*) FROM bank_tokens WHERE provider = '"'"'prior-by'"'"'"' 2>/dev/null | tr -dc '0-9')"
if [ -z "$CONNECTED" ]; then
  echo "⚠ не смог проверить, есть ли подключённые счета Приорбанка (база не ответила)."
elif [ "$CONNECTED" -gt 0 ]; then
  echo "⚠ Подключённых счетов Приорбанка: $CONNECTED. После замены регистрации они перестанут работать,"
  echo "  владельцам счетов придётся подключаться заново."
fi
# ⚠ «The database did not answer» is NOT «no connected accounts»: the step may break them, so an
# unknown count asks too.
if [ -n "$OLD_ID" ] || [ "${CONNECTED:-unknown}" != "0" ]; then
  printf 'Продолжить? Введите «да»: '
  IFS= read -r ANSWER
  [ "$(trim "$ANSWER")" = "да" ] || { echo "Отменено, ничего не менял."; exit 1; }
fi

DOMAIN="$(trim "$(env_value DOMAIN)")"
if ! valid_domain "$DOMAIN"; then
  printf 'Домен приложения (например bank-app.example.by): '
  IFS= read -r DOMAIN
  DOMAIN="$(trim "$DOMAIN")"
  valid_domain "$DOMAIN" || { echo "✗ не похоже на домен"; exit 2; }
fi
REDIRECT="$(redirect_uri "$DOMAIN")"
echo "Адрес возврата: $REDIRECT"

NAME_DEFAULT="$(default_app_name "$DOMAIN")"
printf 'Имя приложения в банке, латиницей [%s]: ' "$NAME_DEFAULT"
IFS= read -r APP_NAME
APP_NAME="$(trim "$APP_NAME")"
[ -n "$APP_NAME" ] || APP_NAME="$NAME_DEFAULT"
valid_app_name "$APP_NAME" || { echo "✗ имя «$APP_NAME» не годится: только латиница, цифры, «.», «_», «-» (3–100 знаков); русский текст — в описание в кабинете"; exit 2; }

echo
echo "Ключи ТЕХНОЛОГИЧЕСКОГО приложения из Магазина API — промышленные, не песочницы."
printf 'client_id техприложения: '
IFS= read -r TECH_ID
TECH_ID="$(trim "$TECH_ID")"
valid_cred "$TECH_ID" || { echo "✗ неожиданные символы в client_id"; exit 2; }
printf 'client_secret техприложения (ввод не отображается): '
IFS= read -r -s TECH_SECRET
echo
TECH_SECRET="$(trim "$TECH_SECRET")"
valid_cred "$TECH_SECRET" || { echo "✗ неожиданные символы в client_secret"; exit 2; }

BACKUP=""
cleanup() { rm -f ${ENV_TMP:+"$ENV_TMP"}; }
trap cleanup EXIT
trap 'cleanup; exit 130' INT TERM HUP

printf '\n── 1–4. Ключ, токен A, регистрация, чтение обратно ──\n'
# ⚠ JSON built by node from the environment of THIS shell would put the secret into an argument;
# instead the values are escaped here and piped. Only the characters valid_cred allows reach this
# point, plus the name and the redirect, which are escaped for JSON below.
json_str() { printf '%s' "$1" | tr -d '\000-\037\177' | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'; }
INPUT="$(printf '{"base":"%s","kid":"%s","name":"%s","redirect":"%s","techId":"%s","techSecret":"%s"}' \
  "$(json_str "$PRIOR_DCR_BASE")" "$PRIOR_KID" "$(json_str "$APP_NAME")" "$(json_str "$REDIRECT")" \
  "$TECH_ID" "$TECH_SECRET")"
OUT="$(printf '%s' "$INPUT" | $DC exec -T backend node -e "$REGISTER_JS" 2>/dev/null)"
unset INPUT TECH_SECRET

if [ "$(result_field "$OUT" OK)" != "1" ]; then
  STAGE="$(result_field "$OUT" STAGE)"; STATUS="$(result_field "$OUT" STATUS)"; ERR="$(result_field "$OUT" ERROR)"
  case "$STAGE" in
    token)
      echo "  ✗ банк не выдал токен техприложению (HTTP ${STATUS:-?}${ERR:+: $ERR})."
      echo "    Проверьте client_id/secret техприложения: нужны ПРОМЫШЛЕННЫЕ ключи." ;;
    register)
      echo "  ✗ регистрация отклонена (HTTP ${STATUS:-?}${ERR:+: $ERR})."
      [ "$STATUS" = "409" ] && echo "    409 — приложение с таким именем уже есть: запустите ещё раз и введите другое имя." ;;
    network) echo "  ✗ не достучался до банка: ${ERR:-нет ответа}" ;;
    *) echo "  ✗ контейнер backend не ответил — он запущен? (make ps)" ;;
  esac
  echo "  .env не менял."
  exit 1
fi

CLIENT_ID="$(result_field "$OUT" CLIENT_ID)"
CLIENT_SECRET="$(result_field "$OUT" CLIENT_SECRET)"
KEY_LINE="$(result_field "$OUT" KEY_LINE)"
FP="$(result_field "$OUT" FP)"
READ_STATUS="$(result_field "$OUT" READ_STATUS)"
READ_FP="$(result_field "$OUT" READ_FP)"
READ_REDIRECT="$(result_field "$OUT" READ_REDIRECT)"
READ_AUTH="$(result_field "$OUT" READ_AUTH)"
unset OUT

echo "  ✓ зарегистрировано: client_id $CLIENT_ID"
valid_cred "$CLIENT_ID" || { echo "  ✗ банк вернул client_id с неожиданными символами — .env не менял"; exit 1; }
if [ -n "$CLIENT_SECRET" ] && ! valid_cred "$CLIENT_SECRET"; then
  echo "  ✗ банк вернул client_secret с неожиданными символами — .env не менял"; exit 1
fi
case "$KEY_LINE" in
  '-----BEGIN PRIVATE KEY-----\n'*'-----END PRIVATE KEY-----\n') ;;
  *) echo "  ✗ ключ не сформировался — .env не менял"; exit 1 ;;
esac

# ⚠ A mismatch here means the registration is unusable and can't be fixed (PUT is 500): stop before
# .env, so the working state of the server stays as it was.
RETRY="    Удалите приложение $CLIENT_ID в кабинете банка и запустите команду снова. .env не менял."
if [ "$READ_STATUS" != "200" ]; then
  echo "  ✗ прочитать регистрацию обратно не удалось (HTTP ${READ_STATUS:-нет}) — без сверки не записываю."
  echo "$RETRY"
  exit 1
fi
if [ "$READ_FP" != "$FP" ]; then
  echo "  ✗ в банке зарегистрирован ДРУГОЙ ключ (отпечаток ${READ_FP:-пусто}, наш $FP)."
  echo "$RETRY"
  exit 1
fi
case "$READ_REDIRECT" in *"\"$REDIRECT\""*) ;; *)
  echo "  ✗ адрес возврата в банке не совпал: $READ_REDIRECT"
  echo "$RETRY"
  exit 1 ;;
esac
case "$READ_AUTH" in *'"private_key_jwt"'*) ;; *)
  echo "  ✗ метод аутентификации в банке не private_key_jwt: $READ_AUTH"
  echo "$RETRY"
  exit 1 ;;
esac
echo "  ✓ прочитано обратно: ключ (отпечаток $FP), адрес возврата и метод совпадают"

printf '\n── 5. Запись в .env ──\n'
BACKUP=".env.bak.$(date +%Y%m%d%H%M%S)"
cp -p ./.env "$BACKUP" || { echo "  ✗ не смог сделать копию .env — ничего не меняю"; exit 1; }
rewrite_env ./.env "$(env_block "$CLIENT_ID" "$CLIENT_SECRET" "$DOMAIN" "$KEY_LINE")" \
  || { echo "  ✗ не смог записать .env (копия: $BACKUP)"; exit 1; }
unset KEY_LINE CLIENT_SECRET
echo "  ✓ PRIOR_OAUTH_* записаны (ключ и секрет на экран не выводятся), прежний .env — в $BACKUP"
# The fingerprint goes to fd 3 for the Makefile's --verify step (stdout is the operator's screen).
{ printf '%s' "$FP" >&3; } 2>/dev/null || true
exit 0
